spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_docente?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
security:
  jwt:
    # clave en BASE64URL (válida para HMAC-SHA256)
    secret: QulywYuiMZzR90QVVIuIZs9UmBAbDkQQvBmYHlRJtfmJPcfZoa7Hkzv-P9Tvy10f5NvAASEt1NAyS4ZGoWHAEw
    access-token-expiration: 900000   # 15 min en ms
    refresh-token-expiration: 1800000 # 30 min en ms (o lo que prefieras)
    
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
    pe.cibertec.gestion_docente: DEBUG
    org.hibernate.orm.jdbc.bind: trace
